package com.vaadin.dev.model;
// Generated Nov 25, 2015 8:58:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Addr generated by hbm2java
 */
@Entity
@Table(name="ADDR"
    ,catalog="Tag"
)
public class Addr  implements java.io.Serializable {


     private BigDecimal addrId;
     private String addrLn1;
     private String addrLn2;
     private String zpCd;
     private String intnatlStateNm;
     private String createUserId;
     private Date createDt;
     private String updtUserId;
     private Date updtDt;
     private String ctryCd;
     private String stateCd;
     private String cityNm;
     private BigDecimal laceLocnId;
     private String cntyNm;

    public Addr() {
    }

	
    public Addr(BigDecimal addrId, String addrLn1, String zpCd, String intnatlStateNm, String createUserId, Date createDt) {
        this.addrId = addrId;
        this.addrLn1 = addrLn1;
        this.zpCd = zpCd;
        this.intnatlStateNm = intnatlStateNm;
        this.createUserId = createUserId;
        this.createDt = createDt;
    }
    public Addr(BigDecimal addrId, String addrLn1, String addrLn2, String zpCd, String intnatlStateNm, String createUserId, Date createDt, String updtUserId, Date updtDt, String ctryCd, String stateCd, String cityNm, BigDecimal laceLocnId, String cntyNm) {
       this.addrId = addrId;
       this.addrLn1 = addrLn1;
       this.addrLn2 = addrLn2;
       this.zpCd = zpCd;
       this.intnatlStateNm = intnatlStateNm;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.updtUserId = updtUserId;
       this.updtDt = updtDt;
       this.ctryCd = ctryCd;
       this.stateCd = stateCd;
       this.cityNm = cityNm;
       this.laceLocnId = laceLocnId;
       this.cntyNm = cntyNm;
    }
   
     @Id 

    
    @Column(name="ADDR_ID", unique=true, nullable=false, scale=0)
    public BigDecimal getAddrId() {
        return this.addrId;
    }
    
    public void setAddrId(BigDecimal addrId) {
        this.addrId = addrId;
    }

    
    @Column(name="ADDR_LN_1", nullable=false, length=80)
    public String getAddrLn1() {
        return this.addrLn1;
    }
    
    public void setAddrLn1(String addrLn1) {
        this.addrLn1 = addrLn1;
    }

    
    @Column(name="ADDR_LN_2", length=80)
    public String getAddrLn2() {
        return this.addrLn2;
    }
    
    public void setAddrLn2(String addrLn2) {
        this.addrLn2 = addrLn2;
    }

    
    @Column(name="ZP_CD", nullable=false, length=12)
    public String getZpCd() {
        return this.zpCd;
    }
    
    public void setZpCd(String zpCd) {
        this.zpCd = zpCd;
    }

    
    @Column(name="INTNATL_STATE_NM", nullable=false, length=80)
    public String getIntnatlStateNm() {
        return this.intnatlStateNm;
    }
    
    public void setIntnatlStateNm(String intnatlStateNm) {
        this.intnatlStateNm = intnatlStateNm;
    }

    
    @Column(name="CREATE_USER_ID", nullable=false, length=80)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DT", nullable=false, length=19)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UPDT_USER_ID", length=80)
    public String getUpdtUserId() {
        return this.updtUserId;
    }
    
    public void setUpdtUserId(String updtUserId) {
        this.updtUserId = updtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDT_DT", length=19)
    public Date getUpdtDt() {
        return this.updtDt;
    }
    
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }

    
    @Column(name="CTRY_CD", length=5)
    public String getCtryCd() {
        return this.ctryCd;
    }
    
    public void setCtryCd(String ctryCd) {
        this.ctryCd = ctryCd;
    }

    
    @Column(name="STATE_CD", length=3)
    public String getStateCd() {
        return this.stateCd;
    }
    
    public void setStateCd(String stateCd) {
        this.stateCd = stateCd;
    }

    
    @Column(name="CITY_NM", length=50)
    public String getCityNm() {
        return this.cityNm;
    }
    
    public void setCityNm(String cityNm) {
        this.cityNm = cityNm;
    }

    
    @Column(name="LACE_LOCN_ID", scale=0)
    public BigDecimal getLaceLocnId() {
        return this.laceLocnId;
    }
    
    public void setLaceLocnId(BigDecimal laceLocnId) {
        this.laceLocnId = laceLocnId;
    }

    
    @Column(name="CNTY_NM", length=80)
    public String getCntyNm() {
        return this.cntyNm;
    }
    
    public void setCntyNm(String cntyNm) {
        this.cntyNm = cntyNm;
    }




}


