package com.vaadin.dev.model;
// Generated Nov 25, 2015 8:58:03 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cntct generated by hbm2java
 */
@Entity
@Table(name="CNTCT"
    ,catalog="Tag"
)
public class Cntct  implements java.io.Serializable {


     private CntctId id;

    public Cntct() {
    }

    public Cntct(CntctId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="addrId", column=@Column(name="ADDR_ID", scale=0) ), 
        @AttributeOverride(name="cntctId", column=@Column(name="CNTCT_ID", scale=0) ), 
        @AttributeOverride(name="othrCntctId", column=@Column(name="OTHR_CNTCT_ID", scale=0) ), 
        @AttributeOverride(name="createUserId", column=@Column(name="CREATE_USER_ID", length=80) ), 
        @AttributeOverride(name="createDt", column=@Column(name="CREATE_DT", length=19) ), 
        @AttributeOverride(name="updtUserId", column=@Column(name="UPDT_USER_ID", length=80) ), 
        @AttributeOverride(name="updtDt", column=@Column(name="UPDT_DT", length=19) ), 
        @AttributeOverride(name="cntctTypeId", column=@Column(name="CNTCT_TYPE_ID", scale=0) ) } )
    public CntctId getId() {
        return this.id;
    }
    
    public void setId(CntctId id) {
        this.id = id;
    }




}


