package com.vaadin.dev.model;
// Generated Nov 25, 2015 8:58:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dba generated by hbm2java
 */
@Entity
@Table(name="DBA"
    ,catalog="Tag"
)
public class Dba  implements java.io.Serializable {


     private BigDecimal dbaId;
     private String dbaNm;
     private Date effctvDt;
     private Date endDt;
     private String createUserId;
     private Date createDt;
     private String updtUserId;
     private Date updtDt;
     private BigDecimal dlrId;
     private BigDecimal dbaLaceId;

    public Dba() {
    }

	
    public Dba(BigDecimal dbaId) {
        this.dbaId = dbaId;
    }
    public Dba(BigDecimal dbaId, String dbaNm, Date effctvDt, Date endDt, String createUserId, Date createDt, String updtUserId, Date updtDt, BigDecimal dlrId, BigDecimal dbaLaceId) {
       this.dbaId = dbaId;
       this.dbaNm = dbaNm;
       this.effctvDt = effctvDt;
       this.endDt = endDt;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.updtUserId = updtUserId;
       this.updtDt = updtDt;
       this.dlrId = dlrId;
       this.dbaLaceId = dbaLaceId;
    }
   
     @Id 

    
    @Column(name="DBA_ID", unique=true, nullable=false, scale=0)
    public BigDecimal getDbaId() {
        return this.dbaId;
    }
    
    public void setDbaId(BigDecimal dbaId) {
        this.dbaId = dbaId;
    }

    
    @Column(name="DBA_NM", length=100)
    public String getDbaNm() {
        return this.dbaNm;
    }
    
    public void setDbaNm(String dbaNm) {
        this.dbaNm = dbaNm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFCTV_DT", length=19)
    public Date getEffctvDt() {
        return this.effctvDt;
    }
    
    public void setEffctvDt(Date effctvDt) {
        this.effctvDt = effctvDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DT", length=19)
    public Date getEndDt() {
        return this.endDt;
    }
    
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }

    
    @Column(name="CREATE_USER_ID", length=80)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DT", length=19)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UPDT_USER_ID", length=80)
    public String getUpdtUserId() {
        return this.updtUserId;
    }
    
    public void setUpdtUserId(String updtUserId) {
        this.updtUserId = updtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDT_DT", length=19)
    public Date getUpdtDt() {
        return this.updtDt;
    }
    
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }

    
    @Column(name="DLR_ID", scale=0)
    public BigDecimal getDlrId() {
        return this.dlrId;
    }
    
    public void setDlrId(BigDecimal dlrId) {
        this.dlrId = dlrId;
    }

    
    @Column(name="DBA_LACE_ID", scale=0)
    public BigDecimal getDbaLaceId() {
        return this.dbaLaceId;
    }
    
    public void setDbaLaceId(BigDecimal dbaLaceId) {
        this.dbaLaceId = dbaLaceId;
    }




}


