package com.vaadin.dev.model;
// Generated Nov 25, 2015 8:58:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlrLicns generated by hbm2java
 */
@Entity
@Table(name="DLR_LICNS"
    ,catalog="Tag"
)
public class DlrLicns  implements java.io.Serializable {


     private DlrLicnsId id;
     private Date effctvDt;
     private Date endDt;
     private String createUserId;
     private Date createDt;
     private String updtUserId;
     private Date updtDt;

    public DlrLicns() {
    }

	
    public DlrLicns(DlrLicnsId id) {
        this.id = id;
    }
    public DlrLicns(DlrLicnsId id, Date effctvDt, Date endDt, String createUserId, Date createDt, String updtUserId, Date updtDt) {
       this.id = id;
       this.effctvDt = effctvDt;
       this.endDt = endDt;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.updtUserId = updtUserId;
       this.updtDt = updtDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="dlrId", column=@Column(name="DLR_ID", nullable=false, scale=0) ), 
        @AttributeOverride(name="licnsId", column=@Column(name="LICNS_ID", nullable=false, scale=0) ) } )
    public DlrLicnsId getId() {
        return this.id;
    }
    
    public void setId(DlrLicnsId id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFCTV_DT", length=19)
    public Date getEffctvDt() {
        return this.effctvDt;
    }
    
    public void setEffctvDt(Date effctvDt) {
        this.effctvDt = effctvDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DT", length=19)
    public Date getEndDt() {
        return this.endDt;
    }
    
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }

    
    @Column(name="CREATE_USER_ID", length=80)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DT", length=19)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="UPDT_USER_ID", length=80)
    public String getUpdtUserId() {
        return this.updtUserId;
    }
    
    public void setUpdtUserId(String updtUserId) {
        this.updtUserId = updtUserId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDT_DT", length=19)
    public Date getUpdtDt() {
        return this.updtDt;
    }
    
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }




}


