package com.vaadin.dev.model;
// Generated Nov 25, 2015 8:58:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DlrLicnsId generated by hbm2java
 */
@Embeddable
public class DlrLicnsId  implements java.io.Serializable {


     private BigDecimal dlrId;
     private BigDecimal licnsId;

    public DlrLicnsId() {
    }

    public DlrLicnsId(BigDecimal dlrId, BigDecimal licnsId) {
       this.dlrId = dlrId;
       this.licnsId = licnsId;
    }
   


    @Column(name="DLR_ID", nullable=false, scale=0)
    public BigDecimal getDlrId() {
        return this.dlrId;
    }
    
    public void setDlrId(BigDecimal dlrId) {
        this.dlrId = dlrId;
    }


    @Column(name="LICNS_ID", nullable=false, scale=0)
    public BigDecimal getLicnsId() {
        return this.licnsId;
    }
    
    public void setLicnsId(BigDecimal licnsId) {
        this.licnsId = licnsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DlrLicnsId) ) return false;
		 DlrLicnsId castOther = ( DlrLicnsId ) other; 
         
		 return ( (this.getDlrId()==castOther.getDlrId()) || ( this.getDlrId()!=null && castOther.getDlrId()!=null && this.getDlrId().equals(castOther.getDlrId()) ) )
 && ( (this.getLicnsId()==castOther.getLicnsId()) || ( this.getLicnsId()!=null && castOther.getLicnsId()!=null && this.getLicnsId().equals(castOther.getLicnsId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDlrId() == null ? 0 : this.getDlrId().hashCode() );
         result = 37 * result + ( getLicnsId() == null ? 0 : this.getLicnsId().hashCode() );
         return result;
   }   


}


