package com.vaadin.dev.model;
// Generated Nov 25, 2015 8:58:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DlrUserId generated by hbm2java
 */
@Embeddable
public class DlrUserId  implements java.io.Serializable {


     private BigDecimal dlrId;
     private BigDecimal userId;

    public DlrUserId() {
    }

    public DlrUserId(BigDecimal dlrId, BigDecimal userId) {
       this.dlrId = dlrId;
       this.userId = userId;
    }



    @Column(name="DLR_ID", nullable=false, scale=0)
    public BigDecimal getDlrId() {
        return this.dlrId;
    }

    public void setDlrId(BigDecimal dlrId) {
        this.dlrId = dlrId;
    }


    @Column(name="USER_ID", nullable=false, scale=0)
    public BigDecimal getUserId() {
        return this.userId;
    }

    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DlrUserId) ) return false;
		 DlrUserId castOther = ( DlrUserId ) other;

		 return ( (this.getDlrId()==castOther.getDlrId()) || ( this.getDlrId()!=null && castOther.getDlrId()!=null && this.getDlrId().equals(castOther.getDlrId()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getDlrId() == null ? 0 : this.getDlrId().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         return result;
   }


}


