package com.vaadin.dev.model;
// Generated Nov 25, 2015 8:58:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OwnrId generated by hbm2java
 */
@Embeddable
public class OwnrId  implements java.io.Serializable {


     private BigDecimal ownrId;
     private String ownrFrstNm;
     private String ownrLastNm;
     private String ownrBsnsNm;
     private Date effctvDt;
     private Date endDt;
     private Byte ownrTypeId;
     private Short sfxTypeId;
     private String createUserId;
     private Date createDt;
     private String updtUserId;
     private Date updtDt;
     private String ownrMdlInitlTxt;

    public OwnrId() {
    }

    public OwnrId(BigDecimal ownrId, String ownrFrstNm, String ownrLastNm, String ownrBsnsNm, Date effctvDt, Date endDt, Byte ownrTypeId, Short sfxTypeId, String createUserId, Date createDt, String updtUserId, Date updtDt, String ownrMdlInitlTxt) {
       this.ownrId = ownrId;
       this.ownrFrstNm = ownrFrstNm;
       this.ownrLastNm = ownrLastNm;
       this.ownrBsnsNm = ownrBsnsNm;
       this.effctvDt = effctvDt;
       this.endDt = endDt;
       this.ownrTypeId = ownrTypeId;
       this.sfxTypeId = sfxTypeId;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.updtUserId = updtUserId;
       this.updtDt = updtDt;
       this.ownrMdlInitlTxt = ownrMdlInitlTxt;
    }
   


    @Column(name="OWNR_ID", scale=0)
    public BigDecimal getOwnrId() {
        return this.ownrId;
    }
    
    public void setOwnrId(BigDecimal ownrId) {
        this.ownrId = ownrId;
    }


    @Column(name="OWNR_FRST_NM", length=33)
    public String getOwnrFrstNm() {
        return this.ownrFrstNm;
    }
    
    public void setOwnrFrstNm(String ownrFrstNm) {
        this.ownrFrstNm = ownrFrstNm;
    }


    @Column(name="OWNR_LAST_NM", length=33)
    public String getOwnrLastNm() {
        return this.ownrLastNm;
    }
    
    public void setOwnrLastNm(String ownrLastNm) {
        this.ownrLastNm = ownrLastNm;
    }


    @Column(name="OWNR_BSNS_NM", length=60)
    public String getOwnrBsnsNm() {
        return this.ownrBsnsNm;
    }
    
    public void setOwnrBsnsNm(String ownrBsnsNm) {
        this.ownrBsnsNm = ownrBsnsNm;
    }


    @Column(name="EFFCTV_DT", length=19)
    public Date getEffctvDt() {
        return this.effctvDt;
    }
    
    public void setEffctvDt(Date effctvDt) {
        this.effctvDt = effctvDt;
    }


    @Column(name="END_DT", length=19)
    public Date getEndDt() {
        return this.endDt;
    }
    
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }


    @Column(name="OWNR_TYPE_ID", precision=2, scale=0)
    public Byte getOwnrTypeId() {
        return this.ownrTypeId;
    }
    
    public void setOwnrTypeId(Byte ownrTypeId) {
        this.ownrTypeId = ownrTypeId;
    }


    @Column(name="SFX_TYPE_ID", precision=3, scale=0)
    public Short getSfxTypeId() {
        return this.sfxTypeId;
    }
    
    public void setSfxTypeId(Short sfxTypeId) {
        this.sfxTypeId = sfxTypeId;
    }


    @Column(name="CREATE_USER_ID", length=80)
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }


    @Column(name="CREATE_DT", length=19)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }


    @Column(name="UPDT_USER_ID", length=80)
    public String getUpdtUserId() {
        return this.updtUserId;
    }
    
    public void setUpdtUserId(String updtUserId) {
        this.updtUserId = updtUserId;
    }


    @Column(name="UPDT_DT", length=19)
    public Date getUpdtDt() {
        return this.updtDt;
    }
    
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }


    @Column(name="OWNR_MDL_INITL_TXT", length=2)
    public String getOwnrMdlInitlTxt() {
        return this.ownrMdlInitlTxt;
    }
    
    public void setOwnrMdlInitlTxt(String ownrMdlInitlTxt) {
        this.ownrMdlInitlTxt = ownrMdlInitlTxt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OwnrId) ) return false;
		 OwnrId castOther = ( OwnrId ) other; 
         
		 return ( (this.getOwnrId()==castOther.getOwnrId()) || ( this.getOwnrId()!=null && castOther.getOwnrId()!=null && this.getOwnrId().equals(castOther.getOwnrId()) ) )
 && ( (this.getOwnrFrstNm()==castOther.getOwnrFrstNm()) || ( this.getOwnrFrstNm()!=null && castOther.getOwnrFrstNm()!=null && this.getOwnrFrstNm().equals(castOther.getOwnrFrstNm()) ) )
 && ( (this.getOwnrLastNm()==castOther.getOwnrLastNm()) || ( this.getOwnrLastNm()!=null && castOther.getOwnrLastNm()!=null && this.getOwnrLastNm().equals(castOther.getOwnrLastNm()) ) )
 && ( (this.getOwnrBsnsNm()==castOther.getOwnrBsnsNm()) || ( this.getOwnrBsnsNm()!=null && castOther.getOwnrBsnsNm()!=null && this.getOwnrBsnsNm().equals(castOther.getOwnrBsnsNm()) ) )
 && ( (this.getEffctvDt()==castOther.getEffctvDt()) || ( this.getEffctvDt()!=null && castOther.getEffctvDt()!=null && this.getEffctvDt().equals(castOther.getEffctvDt()) ) )
 && ( (this.getEndDt()==castOther.getEndDt()) || ( this.getEndDt()!=null && castOther.getEndDt()!=null && this.getEndDt().equals(castOther.getEndDt()) ) )
 && ( (this.getOwnrTypeId()==castOther.getOwnrTypeId()) || ( this.getOwnrTypeId()!=null && castOther.getOwnrTypeId()!=null && this.getOwnrTypeId().equals(castOther.getOwnrTypeId()) ) )
 && ( (this.getSfxTypeId()==castOther.getSfxTypeId()) || ( this.getSfxTypeId()!=null && castOther.getSfxTypeId()!=null && this.getSfxTypeId().equals(castOther.getSfxTypeId()) ) )
 && ( (this.getCreateUserId()==castOther.getCreateUserId()) || ( this.getCreateUserId()!=null && castOther.getCreateUserId()!=null && this.getCreateUserId().equals(castOther.getCreateUserId()) ) )
 && ( (this.getCreateDt()==castOther.getCreateDt()) || ( this.getCreateDt()!=null && castOther.getCreateDt()!=null && this.getCreateDt().equals(castOther.getCreateDt()) ) )
 && ( (this.getUpdtUserId()==castOther.getUpdtUserId()) || ( this.getUpdtUserId()!=null && castOther.getUpdtUserId()!=null && this.getUpdtUserId().equals(castOther.getUpdtUserId()) ) )
 && ( (this.getUpdtDt()==castOther.getUpdtDt()) || ( this.getUpdtDt()!=null && castOther.getUpdtDt()!=null && this.getUpdtDt().equals(castOther.getUpdtDt()) ) )
 && ( (this.getOwnrMdlInitlTxt()==castOther.getOwnrMdlInitlTxt()) || ( this.getOwnrMdlInitlTxt()!=null && castOther.getOwnrMdlInitlTxt()!=null && this.getOwnrMdlInitlTxt().equals(castOther.getOwnrMdlInitlTxt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOwnrId() == null ? 0 : this.getOwnrId().hashCode() );
         result = 37 * result + ( getOwnrFrstNm() == null ? 0 : this.getOwnrFrstNm().hashCode() );
         result = 37 * result + ( getOwnrLastNm() == null ? 0 : this.getOwnrLastNm().hashCode() );
         result = 37 * result + ( getOwnrBsnsNm() == null ? 0 : this.getOwnrBsnsNm().hashCode() );
         result = 37 * result + ( getEffctvDt() == null ? 0 : this.getEffctvDt().hashCode() );
         result = 37 * result + ( getEndDt() == null ? 0 : this.getEndDt().hashCode() );
         result = 37 * result + ( getOwnrTypeId() == null ? 0 : this.getOwnrTypeId().hashCode() );
         result = 37 * result + ( getSfxTypeId() == null ? 0 : this.getSfxTypeId().hashCode() );
         result = 37 * result + ( getCreateUserId() == null ? 0 : this.getCreateUserId().hashCode() );
         result = 37 * result + ( getCreateDt() == null ? 0 : this.getCreateDt().hashCode() );
         result = 37 * result + ( getUpdtUserId() == null ? 0 : this.getUpdtUserId().hashCode() );
         result = 37 * result + ( getUpdtDt() == null ? 0 : this.getUpdtDt().hashCode() );
         result = 37 * result + ( getOwnrMdlInitlTxt() == null ? 0 : this.getOwnrMdlInitlTxt().hashCode() );
         return result;
   }   


}


