package com.vaadin.dev.model;
// Generated Nov 25, 2015 8:58:03 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Plate generated by hbm2java
 */
@Entity
@Table(name="PLATE"
    ,catalog="Tag"
)
public class Plate  implements java.io.Serializable {


     private PlateId id;

    public Plate() {
    }

    public Plate(PlateId id) {
       this.id = id;
    }

     @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="plateId", column=@Column(name="PLATE_ID", scale=0) ),
        @AttributeOverride(name="plateNbr", column=@Column(name="PLATE_NBR", length=8) ),
        @AttributeOverride(name="startDt", column=@Column(name="START_DT", length=19) ),
        @AttributeOverride(name="effctvDt", column=@Column(name="EFFCTV_DT", length=19) ),
        @AttributeOverride(name="endDt", column=@Column(name="END_DT", length=19) ),
        @AttributeOverride(name="plateTypeId", column=@Column(name="PLATE_TYPE_ID", precision=3, scale=0) ),
        @AttributeOverride(name="createUserId", column=@Column(name="CREATE_USER_ID", length=80) ),
        @AttributeOverride(name="createDt", column=@Column(name="CREATE_DT", length=19) ),
        @AttributeOverride(name="updtUserId", column=@Column(name="UPDT_USER_ID", length=80) ),
        @AttributeOverride(name="updtDt", column=@Column(name="UPDT_DT", length=19) ),
        @AttributeOverride(name="plateBirthdate", column=@Column(name="PLATE_BIRTHDATE", length=19) ) } )
    public PlateId getId() {
        return this.id;
    }

    public void setId(PlateId id) {
        this.id = id;
    }




}


