package com.vaadin.dev.model;
// Generated Nov 25, 2015 8:58:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlateId generated by hbm2java
 */
@Embeddable
public class PlateId  implements java.io.Serializable {


     private BigDecimal plateId;
     private String plateNbr;
     private Date startDt;
     private Date effctvDt;
     private Date endDt;
     private Short plateTypeId;
     private String createUserId;
     private Date createDt;
     private String updtUserId;
     private Date updtDt;
     private Date plateBirthdate;

    public PlateId() {
    }

    public PlateId(BigDecimal plateId, String plateNbr, Date startDt, Date effctvDt, Date endDt, Short plateTypeId, String createUserId, Date createDt, String updtUserId, Date updtDt, Date plateBirthdate) {
       this.plateId = plateId;
       this.plateNbr = plateNbr;
       this.startDt = startDt;
       this.effctvDt = effctvDt;
       this.endDt = endDt;
       this.plateTypeId = plateTypeId;
       this.createUserId = createUserId;
       this.createDt = createDt;
       this.updtUserId = updtUserId;
       this.updtDt = updtDt;
       this.plateBirthdate = plateBirthdate;
    }



    @Column(name="PLATE_ID", scale=0)
    public BigDecimal getPlateId() {
        return this.plateId;
    }

    public void setPlateId(BigDecimal plateId) {
        this.plateId = plateId;
    }


    @Column(name="PLATE_NBR", length=8)
    public String getPlateNbr() {
        return this.plateNbr;
    }

    public void setPlateNbr(String plateNbr) {
        this.plateNbr = plateNbr;
    }


    @Column(name="START_DT", length=19)
    public Date getStartDt() {
        return this.startDt;
    }

    public void setStartDt(Date startDt) {
        this.startDt = startDt;
    }


    @Column(name="EFFCTV_DT", length=19)
    public Date getEffctvDt() {
        return this.effctvDt;
    }

    public void setEffctvDt(Date effctvDt) {
        this.effctvDt = effctvDt;
    }


    @Column(name="END_DT", length=19)
    public Date getEndDt() {
        return this.endDt;
    }

    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }


    @Column(name="PLATE_TYPE_ID", precision=3, scale=0)
    public Short getPlateTypeId() {
        return this.plateTypeId;
    }

    public void setPlateTypeId(Short plateTypeId) {
        this.plateTypeId = plateTypeId;
    }


    @Column(name="CREATE_USER_ID", length=80)
    public String getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }


    @Column(name="CREATE_DT", length=19)
    public Date getCreateDt() {
        return this.createDt;
    }

    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }


    @Column(name="UPDT_USER_ID", length=80)
    public String getUpdtUserId() {
        return this.updtUserId;
    }

    public void setUpdtUserId(String updtUserId) {
        this.updtUserId = updtUserId;
    }


    @Column(name="UPDT_DT", length=19)
    public Date getUpdtDt() {
        return this.updtDt;
    }

    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }


    @Column(name="PLATE_BIRTHDATE", length=19)
    public Date getPlateBirthdate() {
        return this.plateBirthdate;
    }

    public void setPlateBirthdate(Date plateBirthdate) {
        this.plateBirthdate = plateBirthdate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlateId) ) return false;
		 PlateId castOther = ( PlateId ) other;

		 return ( (this.getPlateId()==castOther.getPlateId()) || ( this.getPlateId()!=null && castOther.getPlateId()!=null && this.getPlateId().equals(castOther.getPlateId()) ) )
 && ( (this.getPlateNbr()==castOther.getPlateNbr()) || ( this.getPlateNbr()!=null && castOther.getPlateNbr()!=null && this.getPlateNbr().equals(castOther.getPlateNbr()) ) )
 && ( (this.getStartDt()==castOther.getStartDt()) || ( this.getStartDt()!=null && castOther.getStartDt()!=null && this.getStartDt().equals(castOther.getStartDt()) ) )
 && ( (this.getEffctvDt()==castOther.getEffctvDt()) || ( this.getEffctvDt()!=null && castOther.getEffctvDt()!=null && this.getEffctvDt().equals(castOther.getEffctvDt()) ) )
 && ( (this.getEndDt()==castOther.getEndDt()) || ( this.getEndDt()!=null && castOther.getEndDt()!=null && this.getEndDt().equals(castOther.getEndDt()) ) )
 && ( (this.getPlateTypeId()==castOther.getPlateTypeId()) || ( this.getPlateTypeId()!=null && castOther.getPlateTypeId()!=null && this.getPlateTypeId().equals(castOther.getPlateTypeId()) ) )
 && ( (this.getCreateUserId()==castOther.getCreateUserId()) || ( this.getCreateUserId()!=null && castOther.getCreateUserId()!=null && this.getCreateUserId().equals(castOther.getCreateUserId()) ) )
 && ( (this.getCreateDt()==castOther.getCreateDt()) || ( this.getCreateDt()!=null && castOther.getCreateDt()!=null && this.getCreateDt().equals(castOther.getCreateDt()) ) )
 && ( (this.getUpdtUserId()==castOther.getUpdtUserId()) || ( this.getUpdtUserId()!=null && castOther.getUpdtUserId()!=null && this.getUpdtUserId().equals(castOther.getUpdtUserId()) ) )
 && ( (this.getUpdtDt()==castOther.getUpdtDt()) || ( this.getUpdtDt()!=null && castOther.getUpdtDt()!=null && this.getUpdtDt().equals(castOther.getUpdtDt()) ) )
 && ( (this.getPlateBirthdate()==castOther.getPlateBirthdate()) || ( this.getPlateBirthdate()!=null && castOther.getPlateBirthdate()!=null && this.getPlateBirthdate().equals(castOther.getPlateBirthdate()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getPlateId() == null ? 0 : this.getPlateId().hashCode() );
         result = 37 * result + ( getPlateNbr() == null ? 0 : this.getPlateNbr().hashCode() );
         result = 37 * result + ( getStartDt() == null ? 0 : this.getStartDt().hashCode() );
         result = 37 * result + ( getEffctvDt() == null ? 0 : this.getEffctvDt().hashCode() );
         result = 37 * result + ( getEndDt() == null ? 0 : this.getEndDt().hashCode() );
         result = 37 * result + ( getPlateTypeId() == null ? 0 : this.getPlateTypeId().hashCode() );
         result = 37 * result + ( getCreateUserId() == null ? 0 : this.getCreateUserId().hashCode() );
         result = 37 * result + ( getCreateDt() == null ? 0 : this.getCreateDt().hashCode() );
         result = 37 * result + ( getUpdtUserId() == null ? 0 : this.getUpdtUserId().hashCode() );
         result = 37 * result + ( getUpdtDt() == null ? 0 : this.getUpdtDt().hashCode() );
         result = 37 * result + ( getPlateBirthdate() == null ? 0 : this.getPlateBirthdate().hashCode() );
         return result;
   }


}


